### ISSUE TITLE
Request for feature- output file of results

### ISSUE THREAD

**Issue by lkesler** [zach-hartwig/ADAQAnalysis#13]
With the AWESOME new Gaussian fit options, it's kind of a pain to manually extract all the information from the integration section of the analysis tab. Having a feature to get a simple data file output of the integration and fit values would be awesome! Zach is the best.

**Comment by zach-hartwig** [comment]
This is a reasonable request. I'll start implementing and let you know when complete and tested.

**Comment by zach-hartwig** [comment]
Implemented. Let me know if you have further requests on this front. Closing the request.
