### ISSUE TITLE
<3 <3 <3 Error propagation probz

### ISSUE THREAD

**Issue by lkesler** [zach-hartwig/ADAQAnalysis#14]
Zach,

I'm basing what follows on [http://www.phas.ubc.ca/~oser/p509/Lec_10.pdf](url) and [http://www.phas.ubc.ca/~oser/p509/Lec_10.pdf](url). I _think_ the proper error is as follows:

`\Delta A = \sqrt(2\pi)\cdot binwidth \cdot \sqrt(\sigma^2\Delta h^2+h^2\Delta\sigma^2+2\frac{\partial A}{\partial h}\frac{\partial A}{\partial \sigma} \times \rho \Delta\sigma \Delta h)`

Where binwidth is the binwidth in energy units and \rho is the correlation/chi^2 value. 

If you want to wait to implement that mess until we talk, could you just change the output of the file to give these additional parameters: bin width (or number of bins and histogram limits), chi^2, and the calculated integral?

**Comment by zach-hartwig** [comment]
Leigh Ann,

Github didn't interpret your lovely Tex correctly ... lame on them.

This seems reasonable but not fully fleshed out as the partial derivatives still need to be defined in terms of variables that can be multiplied easily in the code. I don't have the equation for A so I suggest that you calculate further.

For implementation, I suggest that you implement a simple ROOT script that creates a gaussian histogram, fits it, and then implements the above formula in code to calculate the proper error. You can post the script here. Then it's easy to modify and drop into the code. If you really want to be pro'n'shit, you can actually implement this within ADAQAnalysis and then submit a pull request. This would make you a contributor (read: immortal fame and unimaginable riches).

**Comment by zach-hartwig** [comment]
Thanks for the hard work and pull request.

**Comment by lkesler** [comment]
Oh man, just looked at the new data file. Noice.
