### ISSUE TITLE
Successful install on Yosemite

### ISSUE THREAD

**Issue by xmatter** [zach-hartwig/ADAQAnalysis#2]
Successfully installed on Yosemite (sort of).  
1)Had to change lboost_thread in Makefile to lboost_thread-mt
2)Change setup.sh: LD_LIBRARY_PATH to DYLD_LIBRARY_PATH

Crashes when trying to run PSD.

**Comment by zach-hartwig** [comment]
Thanks for the update!

This is excellent. I've recently acquired a few year old Mac with OS X. One of the upcoming tasks is ensuring fully compatible of all the ADAQ tools on Mac so this advice is particularly helpful. If you can provide additional information on the crash (what you were doing, stack trace, etc) that would be helpful along with whether other things worked (view waveforms? creating spectra?). The more specific feedback I can gather the better the perfformance on Mac will be. I'm hoping to have this done by mid-August so I'll let you know the progress.
