### ISSUE TITLE
PSD Region w/ Energy Calibration Bug

### ISSUE THREAD

**Issue by sjepeal** [zach-hartwig/ADAQAnalysis#22]
When using the PSD Region creation on a calibrated spectrum, and when the Energy option is selected under the X-axis binning section of the PSD tab, there appears to be a bug regarding determining which data are in the region.  This bug is not apparent when plotting a psd histogram, but when attempting to plot the spectrum with only data from inside the PSD region, a blank spectra appears.  When plotting the spectra outside of the PSD region, all of the data appears.  This is easily worked around by selecting ADC rather than Energy in the PSD tab before creating the PSD region.

**Comment by zach-hartwig** [comment]
I confirm that this bug exists but only when using "waveform data" rather than full waveforms. I will start on a fix...

**Comment by zach-hartwig** [comment]
Thanks for the bug report. This issue has now been fixed in the head of the master branch and will be included in production version 1.8.6.

**Comment by ghost** [comment]
Cool work!
